favicon: null
name: Augusta And Baldwin
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6875
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#2E4C89'
    - '#0C0C0E'
    - '#D7E0E9'
    - '#E12029'
    - '#16DFC7'
  rhythmicContrast: 0.565986
typography_spectrum: 0.1039427
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.00268
analytics:
  twitter: null
  google: null
  facebook: null
