collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1834937
  brandStrength: 0.8733778
  lightness: 0.8091584
  brandColors:
    - '#2E4C89'
    - '#0C0C0E'
    - '#D7E0E9'
    - '#E12029'
    - '#16DFC7'
  rhythmicContrast: 0.565986
typography_spectrum: 0.1039427
layout_spectrum: 0
name: AugustaAndBaldwin
